name: Update Crypto Data

on:
  schedule:
    - cron: '0 * * * *'  # كل ساعة
  workflow_dispatch:     # يسمح بتشغيله يدويًا من GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install streamlit pandas numpy requests scikit-learn PyGithub

      - name: Run Crypto Script
        run: |
          python app.py
        env:
          STREAMLIT_TOKEN: ${{ secrets.STREAMLIT_TOKEN }}
          STREAMLIT_REPO: ${{ secrets.STREAMLIT_REPO }}
          STREAMLIT_BRANCH: ${{ secrets.STREAMLIT_BRANCH }}
